### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Domainesaintroch** [IngridWeck/dsr#17]
je fais un test 
![uploads/49d36cb6-c9e8-4bfb-a318-41ffed3771e3/06 oct. 07 016.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F49d36cb6-c9e8-4bfb-a318-41ffed3771e3%2F06+oct.+07+016.jpg)

**Comment by IngridWeck** [comment]
super-test

**Comment by IngridWeck** [comment]
très bon test! Tu vois ce ticket TEST,  je l'ai déplacé dans la colonne
[Done] en le faisant glisser. Et l'autre je l'ai déplacé dans la
hiérarchie. Si tu veux, tu peux me donner quelques petites tache à faire
pour ma prochaine session (probablement mardi).  :)
