### ISSUE TITLE
salle

### ISSUE THREAD

**Issue by Domainesaintroch** [IngridWeck/dsr#20]
dans les sous-titres, ne vaudrait-il pas mieux mettre salle d'événement plutôt que mariage?

**Comment by IngridWeck** [comment]
ou dans les sous titre ? dans le menu?  "salle d'évènement" c'est beaucoup trop long pour le menu

**Comment by Domainesaintroch** [comment]
ou alors EVENT tout simplement. Juste pour que les gens comprennent qu'on faire autre chose que de se marier.
