### ISSUE TITLE
liens

### ISSUE THREAD

**Issue by Domainesaintroch** [IngridWeck/dsr#21]
je ne suis pas fan du lien "photographe". Voici le lien vers Chloé Thôme : www.chloethome.com et celui de Joëlle Lê www.joellele.be . Pour les fleurs, par exemple, j'adore ceci www.for-me.be

**Comment by IngridWeck** [comment]
C'est à toi de choisir.

**Comment by Domainesaintroch** [comment]
http://thomasmeunier.be/ 
voici un autre photographe qui connait bien le domaine.
Peux-tu mettre les 3 photographes, en espérant que ce ne soit pas trop surchargé...
Thoma, Joelle et Chloé
