### ISSUE TITLE
vidéo

### ISSUE THREAD

**Issue by Domainesaintroch** [IngridWeck/dsr#31]
c'est possible de déjà reprendre les vidéos de l'ancien site (émission tél RTL, RTB jardin extroardinaire,...) ?

**Comment by IngridWeck** [comment]
Bonjour Philippe,

 j’ai intégré une vidéo, en test dans la zone « on en parle dans la presse. 
Je voudrais te montrer comment faire. car c’est quelque chose que tu pourra faire toi même mais il faut que je te montre comment. 

Est-ce que samedi prochain tu as des disponibilités. Je serai à Fleurus vendredi soir. 

Bien à vous

Ingrid

**Comment by Domainesaintroch** [comment]
samedi 15 ? oui je suis là, matin ou a-m, up to you

Le 10 août 2015 09:47, IngridWeck notifications@github.com a écrit :

> Bonjour Philippe,
> 
> j’ai intégré une vidéo, en test dans la zone « on en parle dans la presse.
> Je voudrais te montrer comment faire. car c’est quelque chose que tu
> pourra faire toi même mais il faut que je te montre comment.
> 
> Est-ce que samedi prochain tu as des disponibilités. Je serai à Fleurus
> vendredi soir.
> 
> Bien à vous
> 
> Ingrid
> 
> > Le 9 août 2015 à 12:09, Domainesaintroch notifications@github.com a
> > écrit :
> > 
> > c'est possible de déjà reprendre les vidéos de l'ancien site (émission
> > tél RTL, RTB jardin extroardinaire,...) ?
> > 
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/IngridWeck/dsr/issues/31>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IngridWeck/dsr/issues/31#issuecomment-129342716.

## 

Philippe ROISIN
tél portable : 00.32.498.87.57.00
www.domainesaintroch.be
http://domainesaintroch.blogspot.com
https://www.youtube.com/playlist?list=PLgyIHRuP86rxlywca1-MJjztGelc4eDX2

"Lorsqu'un seul homme rêve, ce n'est qu'un rêve. Mais si beaucoup d'hommes
rêvent ensemble, c'est le début d'une nouvelle réalité"
